### PR TITLE
Issue 28 fix

### PR DESCRIPTION
**Pull request by dmitrym0**
Fixes issue #28 reported by @twibit. This already already includes pull request #29. I added an additional unit test from the original bug report.

### CODE REVIEW

**Comment by dmitrym0** [comment]
re: CI failure for pull request #29, I cannot reproduce it since I dont have a windows machine.

**Comment by dmitrym0** [comment]
Oops, I guess I can't assign multiple people, @danielweck  or @JCCR please review.

**Comment by danielweck** [comment]
Thanks @dmitrym0 
What do you think of these two comments (from me and then @dannyvenier):
https://github.com/readium/readium-cfi-js/pull/29#issuecomment-72761644

**Comment by danielweck** [comment]
@dmitrym0 Oh, I see you added @dannyvenier 's suggested check higher in the code, but you left in the `topLevelElement === 'html'` check untouched (further down, marked as "REFACTORING CANDIDATE"). Let's discuss this further, just to make sure we're not missing something :)

**Comment by dmitrym0** [comment]
@danielweck ah I missed the conversation in the other thread, sorry about that. `topLevelElement` is the common ancestor to the start and end range and so it seems that it can be `<html>`, like if we referencing text inside `<head>` and `<body>` perhaps? I dont understand why it would require the indirection step however (`!`). Perhaps it's worth writing a few more unit tests to cover that case.

**Comment by JCCR** [comment]
@dmitrym0 LGTM

**Pull request merged**
