### PR TITLE
Fix multiple issues (SVG max call-stack, optimize blacklist, jquery.is replacement)

### PR DESCRIPTION
**Pull request by JCCR**
#### Related issue(s) and/or pull request(s)
Original PR | Issue (in commit order):
1. Blacklist optimization: #59 | readium/SDKLauncher-Android#112
2. jQuery.is() replacement: #56 | #40 & #39
3.  SVG max call-stack bug: #60 | readium/readium-shared-js#378

### Additional information
This pull request is three in one.
The other pull requests listed were merged into this single PR because they were dependent with one another and this provides the proper merge conflict resolution.

### CODE REVIEW

**Comment by danielweck** [comment]
the addition of underscore must be checked with higher submodules in the chain (such as shared-js), to avoid duplicated dependencies. (sorry, quick msg from train ;)

**Comment by danielweck** [comment]
suggestion: use the classList API (if available) instead of parse/string-split the element@class attribute when checking the class blacklist (performance penalty if invoked often during DOM tree walking)?

**Comment by JCCR** [comment]
@danielweck 
I originally had classList but after doing some profiling in Chrome I found parsing the class attribute to perform better. Let me double check that.

**Comment by danielweck** [comment]
ah, interesting! :)
(in fact I now remember you mentioning that)

**Comment by danielweck** [comment]
as I suspected:
https://github.com/readium/readium-shared-js/blob/develop/package.cson#L121

I think shared-js must be patched to avoid multiple underscore declarations in the RequireJS build config.

**Comment by danielweck** [comment]
Okay, I created a patch (PR) for `readium-shared-js`:
https://github.com/readium/readium-shared-js/pull/382

**Comment by danielweck** [comment]
I successfully ran the CFI unit tests on Firefox and Chrome. I am testing bookmarking and URL location sharing in `readium-js-viewer` now...

**Comment by danielweck** [comment]
https://github.com/readium/readium-shared-js/issues/378#issuecomment-285324411
`TypeError: classAttribute.split is not a function. (In 'classAttribute.split(' ')', 'classAttribute.split' is undefined)`

**Comment by danielweck** [comment]
Same error in Chrome OSX:
```
Uncaught TypeError: classAttribute.split is not a function
    at SVGDefsElement.<anonymous> (cfi_instructions.js:305)
    at jquery.js:2735
    at Function.grep (jquery.js:433)
    at winnow (jquery.js:2733)
    at jQuery.fn.init.filter (jquery.js:2801)
    at Object.applyBlacklist (cfi_instructions.js:298)
    at Object.createCFIElementSteps (cfi_generator.js:420)
    at Object.generateElementCFIComponent (cfi_generator.js:214)
    at CfiNavigationLogic.getCfiForElement (cfi_navigation_logic.js:628)
    at findVisibleLeafNodeCfi (cfi_navigation_logic.js:930)
```

**Comment by JCCR** [comment]
@danielweck 
thanks, let me update the PR

**Comment by JCCR** [comment]
@danielweck 
I've updated the PR now. Let me know if this looks good. It looks to me like this is the last blocker before we can merge

**Comment by danielweck** [comment]
Looks good to me now.

**Pull request merged**
