### PR TITLE
Fix CFI generation for empty text nodes and comments

### PR DESCRIPTION
**Pull request by Twibit**
#23 : This fixes the CFI generation for empty text nodes counting.

#24 : This fixes the CFI generation for text nodes with comments.

### CODE REVIEW

**Comment by danielweck** [comment]
This PR looks good to me (could someone else CFI-savvy check please?).

**Comment by dmitrym0** [comment]
I can review it next week, if nobody gets to it until then.

**Comment by dmitrym0** [comment]
Hello gentlemen, the pull request looks good to me I have one small questions/request: what is the meaning of the `7` [here](https://github.com/Twibit/readium-cfi-js/commit/d232a722fc28c9c5a8ff8f6e90e9df316ca8e161#diff-c30e728ddc1b4d5a6b094251cdc984deR337) and can we add a comment to the code. 

Otherwise everything looks good. The tests pass, the module builds and the code makes sense.

**Comment by Twibit** [comment]
Hello @dmitrym0 
The `7` is the size of the html comment tag  `<!--[comment]-->`.
The `5` is the size of the instruction processing tag including the required space between the target and the data `<?[target] [data]?>`.

There is still a problem with those node types in the [injectCFIMarkerIntoText](https://github.com/Twibit/readium-cfi-js/blob/develop/src/models/cfi_instructions.js#L146) method. I have a workaround and i'll try to push it with tests tomorrow.

**Comment by dmitrym0** [comment]
Thanks for the explanation. I had to step through to realize that comments are text nodes (obvious in retrospect) and the `<!---->` is part of the string. Merging and closing. Thank you for your contribution!

**Comment by dmitrym0** [comment]
@Twibit as an aside, is `injectCFIMarkerIntoText` actually used?

**Comment by Twibit** [comment]
Yes, it is used to create highlights.

**Pull request merged**
