### PR TITLE
Fix #30: Refactor usage of blacklist, add AMD/CommonJS support

### LINKED ISSUE #30: CFI blacklist (element, class, id)
Related issue: https://github.com/readium/readium-js-viewer/issues/278

The CFI library currently doesn't expose an API to easily customize blacklists across the board (i.e. for all the features that rely on CFI interpretation/generation). There are functions / methods that take blacklist parameters, but this is not integrated consistently. For example (abbreviated code):

https://github.com/readium/readium-shared-js/blob/develop/js/views/cfi_navigation_logic.js#L544

```
this.getFirstVisibleElementCfi = function(topOffset) {

        var foundElement = this.findFirstVisibleElement(topOffset);
...
        var cfi = EPUBcfi.Generator.generateElementCFIComponent(foundElement.$element[0]);
...
        return cfi + "@0:" + foundElement.percentY;
    };
```

Note how `EPUBcfi.Generator.generateElementCFIComponent()` does not take into account default blacklists, let alone custom ones. Yet, the low-level API itself is capable of handling blacklists:

https://github.com/readium/readium-cfi-js/blob/develop/src/models/cfi_generator.js#L161

```
generateElementCFIComponent : function (startElement, classBlacklist, elementBlacklist, idBlacklist) {
...
    },
```

We need a top-level registry of blacklisted elements, classes, ids. There should be a default set (annotation highlights, media overlays character-range highlights, etc.), and this should be configurable when the Readium instance is created (allowing vendor customization, e.g. jQuery "highlight" plugin)

### PR DESCRIPTION
**Pull request by JCCR**
Adds AMD/CommonJS support, and finally removes that redundant test template.

This mainly fixes #30.

New APIs:

`getBlacklist function()`
gets the global blacklist

`setBlacklist: function(blacklistCollection)`
sets the global blacklist

`exampleBlacklistCollection = {
classBlacklist: [...],
elementBlacklist: [...],
idBlacklist: [...]
}`

`appendBlacklist: function(partialBlacklistCollection)`

Merges the partial with the global blacklist, duplicate items are overwritten (similar to $.extend behaviour)

See the new tests for more detail.

### CODE REVIEW

**Comment by danielweck** [comment]
Very cool @JCCR 

Note that the template does not even exist anymore in the feature/plugins branch of readium-cfi-js, as this is an anti-pattern with respect to the RequireJS build process. The newly AMD'ed CFI lib now defines its internal dependencies properly, and takes part in the overall tree of dependencies that allows building the final Readium build artifacts at any level of the chain (i.e. single Almond'ed bundle, or multiple bundles of modules, in shared-js, readium-js, or js-viewer).

Do you have a working example of the blacklist on the "client side" (shared-js calls). I guess we have to refactor all API consumers before we can merge to develop, right? Then I'll align the plugins branch, to keep everything merge-ready :)

**Comment by JCCR** [comment]
@danielweck 
Ah I see, I didn't know you had taken a look at this in regards to the new dep. injection.

And No I don't have a working example on the client side yet, I'll get to that in a bit.

**Comment by danielweck** [comment]
Apart from the `erb` templates and the Grunt build file changes (which do not exist anymore), this PR should update pretty straight-forwardly to match the latest AMD-RequireJS refactoring. Obviously, client-side usage of the proposed "CFI blacklist" API would still need to be updated accordingly.

**Comment by JCCR** [comment]
Closing as it is stale

**Pull request closed without merging**
