### PR TITLE
Add a unit test to check CFI range generation when start and end node do...

### PR DESCRIPTION
**Pull request by Twibit**
...n't have the same level

Related to https://github.com/readium/readium-cfi-js/issues/28

### CODE REVIEW

**Comment by danielweck** [comment]
FYI: I've just tested your new unit test entry, and Karma (Chrome 40.0.2214 on Windows 8.1) now indeed fails when the `grunt` command is invoked (my main development machine is OSX, but as you can see I am double-checking the build processes under my secondary Windows box)

**Comment by danielweck** [comment]
I fixed it locally (code not on GitHub) by replacing:

https://github.com/readium/readium-cfi-js/blob/develop/src/models/cfi_generator.js#L406

```
if (topLevelElement === 'html') {
    return "!" + elementStep;
} else {
    return elementStep;
}
```

with:

```
if (topLevelElement === 'html') {
    return "!" + elementStep;
} else {
    if ($currNode.is(topLevelElement)) {
        return "";
    } else {
        return elementStep;
    }
}
```

...but I'm not 100% sure this is correct. Can anyone review?

**Comment by dannyvenier** [comment]
I'm not sure we'll ever see the case where the topLevelElement (which is the common ancestor of the elements of a range) is 'html' since we typically have a 'body' element wrapping content.   That would assume we have two elements in different 'body' tags which is illegal as far as I know.

I believe you need to handle the $currNode.is(topLevelElement) case and set to "" no matter what, whether topLevelElement is html or not (which it shouldn't be), otherwise you could duplicate the common element step as is the current defect.

So I would add a conditional clause prior to the html check to be sure:
 // --- new clause ---
 if ($currNode.is(topLevelElement)) {
     elementStep = "";
 }
// --- end new clause ---
...
if (topLevelElement === 'html') {
    return "!" + elementStep;
} else {
    return elementStep;
}

**Comment by danielweck** [comment]
Thanks @dannyvenier 
Could you please review @dmitrym0 's Pull Request?
https://github.com/readium/readium-cfi-js/pull/32
Many thanks!

**Pull request merged**
