### PR TITLE
Basic escaping of idref value

### PR DESCRIPTION
**Pull request by marcuswu**
I ran across a book with idrefs like PROLOGUE.xhtml. Directly using this as a selector will look for a tag with id PROLOGUE and class xhtml rather than a tag with id PROLOGUE.xhtml.

This escaping is very basic. Something more involved is probably necessary to escape other CSS operators as well, but at this point I am unable to spend extra time researching and building something more robust.

### CODE REVIEW

**Comment by danielweck** [comment]
I suggest using `ReadiumSDK.Helpers.escapeJQuerySelector()` instead:
https://github.com/readium/readium-shared-js/blob/develop/js/helpers.js#L585

Some time ago, I logged an issue about this:
https://github.com/readium/readium-shared-js/issues/47

These might need escaping as well (attribute value selectors, not # UID):

`generatePackageDocumentCFIComponent`:
`$("itemref[idref='" + contentDocumentName + "']", $(packageDocument))`

`validatePackageDocument`:
`$("itemref[idref='" + contentDocumentName + "']", packageDocument)`

@marcuswu, what do you think?

**Comment by marcuswu** [comment]
I think escapeJQuerySelector() is exactly the kind of thing that is needed. However as you mentioned in the readium-shared-js issue, I also agree that escapeJQuerySelector() is not really supposed to be visible to readium-cfi-js. It seems that both projects have a similar dependency. It would be nice if both requirements could be met without the dependency being included twice. If I am not mistaken, this project is built and the result included in the super project. It would be difficult for the sub projects to maintain their independence as stand-alone libraries while also eliminating duplicate dependencies in the super project.

I think you are also correct that there are other places that could use escaping.

**Comment by danielweck** [comment]
Related: https://github.com/readium/readium-cfi-js/pull/66

**Comment by danielweck** [comment]
This PR is now obsolete, thanks to https://github.com/readium/readium-cfi-js/pull/66 ( @JCCR ), and because @evanmuller updated the Bibliolabs codebase with @JCCR 's code.

**Pull request closed without merging**
